name: drl_env
channels:
  - pytorch
  - defaults
dependencies:
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - colorama=0.4.4
  - cudatoolkit=10.2.89
  - debugpy=1.5.1
  - decorator=5.1.0
  - entrypoints=0.3
  - freetype=2.10.4
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jpeg=9d
  - jupyter_client=7.0.6
  - jupyter_core=4.9.1
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.0
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nest-asyncio=1.5.1
  - olefile=0.46
  - openssl=1.1.1l
  - parso=0.8.2
  - pickleshare=0.7.5
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - pygments=2.10.0
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - pywin32=228
  - pyzmq=22.3.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - torchaudio=0.10.0
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.37.0
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - ale-py==0.7.3
    - astunparse==1.6.3
    - cachetools==4.2.4
    - charset-normalizer==2.0.9
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - flatbuffers==2.0
    - fonttools==4.28.3
    - gast==0.4.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.42.0
    - gym==0.21.0
    - h5py==3.6.0
    - idna==3.3
    - importlib-metadata==4.8.2
    - importlib-resources==5.4.0
    - joblib==1.2.0
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - libclang==14.0.6
    - markdown==3.3.6
    - matplotlib==3.5.1
    - networkx==2.6.3
    - numpy==1.22.4
    - oauthlib==3.1.1
    - opencv-python==4.5.4.60
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.3.4
    - pillow==9.1.1
    - protobuf==3.19.1
    - pyaml==21.10.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.21
    - pyparsing==3.0.6
    - pytz==2021.3
    - pyyaml==6.0
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - sb3-contrib==1.5.0
    - scikit-learn==1.2.2
    - scikit-optimize==0.9.0
    - scipy==1.7.3
    - setuptools==62.3.2
    - stable-baselines3==1.5.0
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.10.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - wrapt==1.13.3
    - zipp==3.6.0
