wandb_version: 1

policy_type:
  desc: null
  value: MaskableActorCriticPolicy
total_timesteps:
  desc: null
  value: 1000000
env_name:
  desc: null
  value: complete
_wandb:
  desc: null
  value:
    code_path: code/scenarios/train_DRL.py
    python_version: 3.11.4
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690890515.022191
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 22
      - 23
      - 35
      4: 3.11.4
      5: 0.15.7
      8:
      - 3
      - 5
algo:
  desc: null
  value: MaskablePPO
policy_class:
  desc: null
  value: <class 'sb3_contrib.common.maskable.policies.MaskableActorCriticPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 1000000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1690890520143624900
learning_rate:
  desc: null
  value: 0.0001
tensorboard_log:
  desc: null
  value: None
_last_obs:
  desc: null
  value: "[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n\
    \  0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'True'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x00000200373A6F10>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: "Box(0.0, [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000\n\
    \ 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000\n 1.00000000e+000\
    \ 1.00000000e+000 1.00000000e+000 1.00000000e+000\n 1.30000000e+001 1.30000000e+001\
    \ 1.30000000e+001 1.30000000e+001\n 1.30000000e+001 1.30000000e+001 1.30000000e+001\
    \ 1.30000000e+001\n 1.30000000e+001 1.30000000e+001 1.30000000e+001 1.30000000e+001\n\
    \ 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000\n 1.00000000e+000\
    \ 1.00000000e+000 1.00000000e+000 1.00000000e+000\n 1.00000000e+000 1.00000000e+000\
    \ 1.00000000e+000 1.00000000e+000\n 1.00000000e+000 1.79769313e+308], (38,), float64)"
action_space:
  desc: null
  value: Discrete(25)
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 100000
gamma:
  desc: null
  value: 1
gae_lambda:
  desc: null
  value: 0.95
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x0000020039E59F80>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x0000020039E5A5C0>
policy:
  desc: null
  value: "MaskableActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n\
    \    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor):\
    \ FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor):\
    \ FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (policy_net): Sequential(\n      (0): Linear(in_features=38,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=38, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=25, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
rollout_buffer:
  desc: null
  value: <sb3_contrib.common.maskable.buffers.MaskableRolloutBuffer object at 0x0000020039E5E8D0>
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x0000020039E5E0D0>
