wandb_version: 1

policy_type:
  desc: null
  value: MaskableActorCriticPolicy
total_timesteps:
  desc: null
  value: 1000000
env_name:
  desc: null
  value: complete
_wandb:
  desc: null
  value:
    code_path: code/scenarios/train_DRL.py
    python_version: 3.11.4
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690886501.190065
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 22
      - 23
      - 35
      4: 3.11.4
      5: 0.15.7
      8:
      - 3
      - 5
